
start: stop
	/bin/bash bash/proc/start.sh ../../.env PROCESS_FLAG /bin/bash run.sh

stop:
	/bin/bash bash/proc/kill.sh ../../.env PROCESS_FLAG

status:
	/bin/bash bash/proc/status.sh ../../.env PROCESS_FLAG

